- name: System Upgrade
  yum: name=* state=latest
  when: common_system_upgrade and (init == '1' or init == 1) and ansible_distribution_major_version != "8"

- name: System Upgrade
  dnf: name=* state=latest
  when: common_system_upgrade and (init == '1' or init == 1) and ansible_distribution_major_version == "8"

- name: OracleLinux8 create pip softlink
  shell: |
    ln -sf /usr/bin/pip-3 /usr/bin/pip3
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == "8"
  
- name: Install Extra Packages for Enterprise Linux on {{ansible_distribution}}, exclude Amazon because scl will cause yum update error
  yum: 
    name: [epel-release,centos-release-scl]
    update_cache: yes
    state: latest
  when: ansible_distribution != 'Amazon' and ansible_distribution != 'OracleLinux'

- name: Install epel repo for OracleLinux
  yum:
    name: oracle-epel-release-el{{ansible_distribution_major_version}}
  when: ansible_distribution == 'OracleLinux'

- name: Install scl repo for OracleLinux
  yum:
    name: scl-utils
  when: ansible_distribution == 'OracleLinux'
  
- block:
  - name: Install Extra Packages for Enterprise Linux on {{ansible_distribution}},there is [releaseserver] in the linux repo,so download from websoft9 self repo 
    shell: |
      amazon-linux-extras install epel -y
      wget -O /etc/yum.repos.d/CentOS7-Base.repo https://raw.githubusercontent.com/websoft9/role_common/master/files/CentOS7-Base.repo

  - name: delete amazon repo priority
    lineinfile:
        dest: "{{item}}"
        regexp: "^priority"
        state: absent
    loop:
      - /etc/yum.repos.d/amzn2-extras.repo
      - /etc/yum.repos.d/amzn2-core.repo
  when: ansible_distribution == 'Amazon'

- block:
  - name: Install Common Software
    yum: 
      name: [mosh,wget,openssl,unzip,bzip2,expect,at,tree,vim,screen,pwgen,git,htop,ImageMagick,inotify-tools,libselinux-python,yum-utils,gcc,jq,telnet]
    when: ansible_distribution != 'OracleLinux'
  
  - name: intall mlocate
    shell: |
      yum install mlocate -y
      updatedb
  when: common_install_components and ansible_distribution != 'OracleLinux'
  
- name: Disable SELinux temporarily
  shell: sudo setenforce 0
  when: ansible_selinux.status != 'disabled'

- name: Disable SELinux ermanently
  selinux:
    state: disabled
  when: ansible_selinux.status != 'disabled'
  
- name: Setting rc.d 0750
  file:
    path: /etc/rc.d/rc.local
    mode: 0750
  when: common_set_rclocal


# install docker on CentOS
- block:
  - name: Install required packages
    yum:
      name: [device-mapper-persistent-data,lvm2]

  - name: Add Docker repository
    shell: wget -O /etc/yum.repos.d/docker-ce.repo {{common_repository_url}}
    
  - name: Update release server
    shell: sudo sed -i "s/\$releasever/7/g" /etc/yum.repos.d/docker-ce.repo
    when: ansible_distribution == 'Amazon'

  - name: Install Docker on {{ansible_distribution}}
    yum:
      name: [docker-ce,docker-ce-cli,containerd.io]
      update_cache: yes
      state: latest
  when: common_install_docker
